#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CODE_NCDB")]
public partial class Code_DBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertmainTable(mainTable instance);
  partial void UpdatemainTable(mainTable instance);
  partial void DeletemainTable(mainTable instance);
  #endregion
	
	public Code_DBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CODE_NCDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Code_DBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Code_DBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Code_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Code_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<mainTable> mainTables
	{
		get
		{
			return this.GetTable<mainTable>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getFatalityDataForPsition")]
	public ISingleResult<getFatalityDataForPsitionResult> getFatalityDataForPsition()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<getFatalityDataForPsitionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getNoInjuryDataForPsition")]
	public ISingleResult<getNoInjuryDataForPsitionResult> getNoInjuryDataForPsition()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<getNoInjuryDataForPsitionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getInjuryDataForPsition")]
	public ISingleResult<getInjuryDataForPsitionResult> getInjuryDataForPsition()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<getInjuryDataForPsitionResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mainTable")]
public partial class mainTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _C_YEAR;
	
	private string _C_MNTH;
	
	private string _C_WDAY;
	
	private string _C_HOUR;
	
	private string _C_SEV;
	
	private string _C_VEHS;
	
	private string _C_CONF;
	
	private string _C_RCFG;
	
	private string _C_WTHR;
	
	private string _C_RSUR;
	
	private string _C_RALN;
	
	private string _C_TRAF;
	
	private string _V_ID;
	
	private string _V_TYPE;
	
	private string _V_YEAR;
	
	private string _P_ID;
	
	private string _P_SEX;
	
	private string _P_AGE;
	
	private string _P_PSN;
	
	private string _P_ISEV;
	
	private string _P_SAFE;
	
	private string _P_USER;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnC_YEARChanging(string value);
    partial void OnC_YEARChanged();
    partial void OnC_MNTHChanging(string value);
    partial void OnC_MNTHChanged();
    partial void OnC_WDAYChanging(string value);
    partial void OnC_WDAYChanged();
    partial void OnC_HOURChanging(string value);
    partial void OnC_HOURChanged();
    partial void OnC_SEVChanging(string value);
    partial void OnC_SEVChanged();
    partial void OnC_VEHSChanging(string value);
    partial void OnC_VEHSChanged();
    partial void OnC_CONFChanging(string value);
    partial void OnC_CONFChanged();
    partial void OnC_RCFGChanging(string value);
    partial void OnC_RCFGChanged();
    partial void OnC_WTHRChanging(string value);
    partial void OnC_WTHRChanged();
    partial void OnC_RSURChanging(string value);
    partial void OnC_RSURChanged();
    partial void OnC_RALNChanging(string value);
    partial void OnC_RALNChanged();
    partial void OnC_TRAFChanging(string value);
    partial void OnC_TRAFChanged();
    partial void OnV_IDChanging(string value);
    partial void OnV_IDChanged();
    partial void OnV_TYPEChanging(string value);
    partial void OnV_TYPEChanged();
    partial void OnV_YEARChanging(string value);
    partial void OnV_YEARChanged();
    partial void OnP_IDChanging(string value);
    partial void OnP_IDChanged();
    partial void OnP_SEXChanging(string value);
    partial void OnP_SEXChanged();
    partial void OnP_AGEChanging(string value);
    partial void OnP_AGEChanged();
    partial void OnP_PSNChanging(string value);
    partial void OnP_PSNChanged();
    partial void OnP_ISEVChanging(string value);
    partial void OnP_ISEVChanged();
    partial void OnP_SAFEChanging(string value);
    partial void OnP_SAFEChanged();
    partial void OnP_USERChanging(string value);
    partial void OnP_USERChanged();
    #endregion
	
	public mainTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_YEAR", DbType="NVarChar(MAX)")]
	public string C_YEAR
	{
		get
		{
			return this._C_YEAR;
		}
		set
		{
			if ((this._C_YEAR != value))
			{
				this.OnC_YEARChanging(value);
				this.SendPropertyChanging();
				this._C_YEAR = value;
				this.SendPropertyChanged("C_YEAR");
				this.OnC_YEARChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_MNTH", DbType="NVarChar(MAX)")]
	public string C_MNTH
	{
		get
		{
			return this._C_MNTH;
		}
		set
		{
			if ((this._C_MNTH != value))
			{
				this.OnC_MNTHChanging(value);
				this.SendPropertyChanging();
				this._C_MNTH = value;
				this.SendPropertyChanged("C_MNTH");
				this.OnC_MNTHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_WDAY", DbType="NVarChar(MAX)")]
	public string C_WDAY
	{
		get
		{
			return this._C_WDAY;
		}
		set
		{
			if ((this._C_WDAY != value))
			{
				this.OnC_WDAYChanging(value);
				this.SendPropertyChanging();
				this._C_WDAY = value;
				this.SendPropertyChanged("C_WDAY");
				this.OnC_WDAYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_HOUR", DbType="NVarChar(MAX)")]
	public string C_HOUR
	{
		get
		{
			return this._C_HOUR;
		}
		set
		{
			if ((this._C_HOUR != value))
			{
				this.OnC_HOURChanging(value);
				this.SendPropertyChanging();
				this._C_HOUR = value;
				this.SendPropertyChanged("C_HOUR");
				this.OnC_HOURChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_SEV", DbType="NVarChar(MAX)")]
	public string C_SEV
	{
		get
		{
			return this._C_SEV;
		}
		set
		{
			if ((this._C_SEV != value))
			{
				this.OnC_SEVChanging(value);
				this.SendPropertyChanging();
				this._C_SEV = value;
				this.SendPropertyChanged("C_SEV");
				this.OnC_SEVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_VEHS", DbType="NVarChar(MAX)")]
	public string C_VEHS
	{
		get
		{
			return this._C_VEHS;
		}
		set
		{
			if ((this._C_VEHS != value))
			{
				this.OnC_VEHSChanging(value);
				this.SendPropertyChanging();
				this._C_VEHS = value;
				this.SendPropertyChanged("C_VEHS");
				this.OnC_VEHSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CONF", DbType="NVarChar(MAX)")]
	public string C_CONF
	{
		get
		{
			return this._C_CONF;
		}
		set
		{
			if ((this._C_CONF != value))
			{
				this.OnC_CONFChanging(value);
				this.SendPropertyChanging();
				this._C_CONF = value;
				this.SendPropertyChanged("C_CONF");
				this.OnC_CONFChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_RCFG", DbType="NVarChar(MAX)")]
	public string C_RCFG
	{
		get
		{
			return this._C_RCFG;
		}
		set
		{
			if ((this._C_RCFG != value))
			{
				this.OnC_RCFGChanging(value);
				this.SendPropertyChanging();
				this._C_RCFG = value;
				this.SendPropertyChanged("C_RCFG");
				this.OnC_RCFGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_WTHR", DbType="NVarChar(MAX)")]
	public string C_WTHR
	{
		get
		{
			return this._C_WTHR;
		}
		set
		{
			if ((this._C_WTHR != value))
			{
				this.OnC_WTHRChanging(value);
				this.SendPropertyChanging();
				this._C_WTHR = value;
				this.SendPropertyChanged("C_WTHR");
				this.OnC_WTHRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_RSUR", DbType="NVarChar(MAX)")]
	public string C_RSUR
	{
		get
		{
			return this._C_RSUR;
		}
		set
		{
			if ((this._C_RSUR != value))
			{
				this.OnC_RSURChanging(value);
				this.SendPropertyChanging();
				this._C_RSUR = value;
				this.SendPropertyChanged("C_RSUR");
				this.OnC_RSURChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_RALN", DbType="NVarChar(MAX)")]
	public string C_RALN
	{
		get
		{
			return this._C_RALN;
		}
		set
		{
			if ((this._C_RALN != value))
			{
				this.OnC_RALNChanging(value);
				this.SendPropertyChanging();
				this._C_RALN = value;
				this.SendPropertyChanged("C_RALN");
				this.OnC_RALNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_TRAF", DbType="NVarChar(MAX)")]
	public string C_TRAF
	{
		get
		{
			return this._C_TRAF;
		}
		set
		{
			if ((this._C_TRAF != value))
			{
				this.OnC_TRAFChanging(value);
				this.SendPropertyChanging();
				this._C_TRAF = value;
				this.SendPropertyChanged("C_TRAF");
				this.OnC_TRAFChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_ID", DbType="NVarChar(MAX)")]
	public string V_ID
	{
		get
		{
			return this._V_ID;
		}
		set
		{
			if ((this._V_ID != value))
			{
				this.OnV_IDChanging(value);
				this.SendPropertyChanging();
				this._V_ID = value;
				this.SendPropertyChanged("V_ID");
				this.OnV_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_TYPE", DbType="NVarChar(MAX)")]
	public string V_TYPE
	{
		get
		{
			return this._V_TYPE;
		}
		set
		{
			if ((this._V_TYPE != value))
			{
				this.OnV_TYPEChanging(value);
				this.SendPropertyChanging();
				this._V_TYPE = value;
				this.SendPropertyChanged("V_TYPE");
				this.OnV_TYPEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_YEAR", DbType="NVarChar(MAX)")]
	public string V_YEAR
	{
		get
		{
			return this._V_YEAR;
		}
		set
		{
			if ((this._V_YEAR != value))
			{
				this.OnV_YEARChanging(value);
				this.SendPropertyChanging();
				this._V_YEAR = value;
				this.SendPropertyChanged("V_YEAR");
				this.OnV_YEARChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="NVarChar(MAX)")]
	public string P_ID
	{
		get
		{
			return this._P_ID;
		}
		set
		{
			if ((this._P_ID != value))
			{
				this.OnP_IDChanging(value);
				this.SendPropertyChanging();
				this._P_ID = value;
				this.SendPropertyChanged("P_ID");
				this.OnP_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_SEX", DbType="NVarChar(MAX)")]
	public string P_SEX
	{
		get
		{
			return this._P_SEX;
		}
		set
		{
			if ((this._P_SEX != value))
			{
				this.OnP_SEXChanging(value);
				this.SendPropertyChanging();
				this._P_SEX = value;
				this.SendPropertyChanged("P_SEX");
				this.OnP_SEXChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_AGE", DbType="NVarChar(MAX)")]
	public string P_AGE
	{
		get
		{
			return this._P_AGE;
		}
		set
		{
			if ((this._P_AGE != value))
			{
				this.OnP_AGEChanging(value);
				this.SendPropertyChanging();
				this._P_AGE = value;
				this.SendPropertyChanged("P_AGE");
				this.OnP_AGEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_PSN", DbType="NVarChar(MAX)")]
	public string P_PSN
	{
		get
		{
			return this._P_PSN;
		}
		set
		{
			if ((this._P_PSN != value))
			{
				this.OnP_PSNChanging(value);
				this.SendPropertyChanging();
				this._P_PSN = value;
				this.SendPropertyChanged("P_PSN");
				this.OnP_PSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ISEV", DbType="NVarChar(MAX)")]
	public string P_ISEV
	{
		get
		{
			return this._P_ISEV;
		}
		set
		{
			if ((this._P_ISEV != value))
			{
				this.OnP_ISEVChanging(value);
				this.SendPropertyChanging();
				this._P_ISEV = value;
				this.SendPropertyChanged("P_ISEV");
				this.OnP_ISEVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_SAFE", DbType="NVarChar(MAX)")]
	public string P_SAFE
	{
		get
		{
			return this._P_SAFE;
		}
		set
		{
			if ((this._P_SAFE != value))
			{
				this.OnP_SAFEChanging(value);
				this.SendPropertyChanging();
				this._P_SAFE = value;
				this.SendPropertyChanged("P_SAFE");
				this.OnP_SAFEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_USER", DbType="NVarChar(MAX)")]
	public string P_USER
	{
		get
		{
			return this._P_USER;
		}
		set
		{
			if ((this._P_USER != value))
			{
				this.OnP_USERChanging(value);
				this.SendPropertyChanging();
				this._P_USER = value;
				this.SendPropertyChanged("P_USER");
				this.OnP_USERChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class getFatalityDataForPsitionResult
{
	
	private string _Position;
	
	private System.Nullable<int> _PositionCount;
	
	public getFatalityDataForPsitionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(MAX)")]
	public string Position
	{
		get
		{
			return this._Position;
		}
		set
		{
			if ((this._Position != value))
			{
				this._Position = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionCount", DbType="Int")]
	public System.Nullable<int> PositionCount
	{
		get
		{
			return this._PositionCount;
		}
		set
		{
			if ((this._PositionCount != value))
			{
				this._PositionCount = value;
			}
		}
	}
}

public partial class getNoInjuryDataForPsitionResult
{
	
	private string _Position;
	
	private System.Nullable<int> _PositionCount;
	
	public getNoInjuryDataForPsitionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(MAX)")]
	public string Position
	{
		get
		{
			return this._Position;
		}
		set
		{
			if ((this._Position != value))
			{
				this._Position = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionCount", DbType="Int")]
	public System.Nullable<int> PositionCount
	{
		get
		{
			return this._PositionCount;
		}
		set
		{
			if ((this._PositionCount != value))
			{
				this._PositionCount = value;
			}
		}
	}
}

public partial class getInjuryDataForPsitionResult
{
	
	private string _Position;
	
	private System.Nullable<int> _PositionCount;
	
	public getInjuryDataForPsitionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(MAX)")]
	public string Position
	{
		get
		{
			return this._Position;
		}
		set
		{
			if ((this._Position != value))
			{
				this._Position = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionCount", DbType="Int")]
	public System.Nullable<int> PositionCount
	{
		get
		{
			return this._PositionCount;
		}
		set
		{
			if ((this._PositionCount != value))
			{
				this._PositionCount = value;
			}
		}
	}
}
#pragma warning restore 1591
